development:
  adapter: postgresql
  encoding: unicode
  database: home_budget_development
  host: localhost
  pool: 5
  username: postgresuser
  password: Password1

production:
  adapter: postgresql
  encoding: unicode
  database: d3s0ocsjmnb7gh
  pool: 8
  username: vdkdnuauaayqcd
  password: 40de8f41c155e405aedae663468f4f2a9f32e2aadcd369eca3d15ec7b9ec77cc
  host: ec2-54-83-19-244.compute-1.amazonaws.com
  port: 5432
